###회원 가입 API
POST http://localhost:8080/api/v1/members
Content-Type: application/json

{
"name" : "테스트랑께"
}


###회원 가입 API2
POST http://localhost:8080/api/v2/members
Content-Type: application/json

{
"name" : "테스트랑께"
}


###회원 수정 API
PUT http://localhost:8080/api/v2/members/1
Content-Type: application/json

{
"name" : "수정이랑꼐랑까랑"
}

###회원 조회
GET http://localhost:8080/api/v1/members
Content-Type: application/json


###회원 조회2
GET http://localhost:8080/api/v2/members
Content-Type: application/json


